### ISSUE TITLE
Could you please share the download link of dataset again?

### ISSUE THREAD

**Issue by pooffre** [DreamtaleCore/Refool#15]
Could you please share the download link of dataset again? The original link is invalid, very needed, thank you!

**Comment by DreamtaleCore** [comment]
Hi, you can access it from [here](https://bhpan.buaa.edu.cn:443/link/FB79C3F1181722911F07EE1C381F96C7)

**Comment by pooffre** [comment]
Thanks a lot !

**Comment by persistz** [comment]
Hi Yunfei @DreamtaleCore ,
The link is invalid again, can you update it a second time?
