### ISSUE TITLE
Issue regarding 20% in-class poisoning rate

### ISSUE THREAD

**Issue by jyuteo09** [DreamtaleCore/Refool#2]
I was trying to realize the attack to get the attack success rate stated in Table 2 of the paper for GTSRB dataset.

The paper states that '0' class is the targeted class of attack and 20% of images from class '0' is poisoned (since it is clean-label attack), and the injection rate is 3.16% in this case. Therefore, I used the `GTSRB/train-file/train-0-0.2.txt` to train the model which I downloaded from the link given.

In README of GTSRB, it says that the '0-0.2' in the .txt file means that 20% of images in the target class '0 are poisoned images. In actual, in the `train-file/train-0-0.2.txt`, there are a total of 4849 training images. In the target class '0', there are 307 clean images and 154 poisoned images. The injection rate is around 3.16% (154 images out of 4849 training images). However, it is not 20% of the images of class '0' (154 poisoned images out of 461 images in class '0').

The same problem applies to almost all of the .txt files in the `GTSRB/train-file` folder.

Is the `GTSRB/train-file/train-0-0.2.txt` being used to train the poisoned model for GTSRB dataset as mentioned in the paper?

Is 20% of images from class '0' being injected with reflection during training of GTSRB model to achieve the result in Table 2 of the paper?

**Comment by DreamtaleCore** [comment]
Hi,

We have checked the dataset, and the latest one could be found in `dataset/download.txt`

Best
